### ISSUE TITLE
Cron format wrong

### ISSUE THREAD

**Issue by ntimo** [Promaethius/mailcow-dind#12]
Hello,
I just created this docker-compose file that I later want to use with some tweaks for deployment inside of a swarm. But I am always getting this error:

<img width="907" alt="bildschirmfoto 2019-01-11 um 19 40 59" src="https://user-images.githubusercontent.com/6145026/51053137-1cfdea80-15d9-11e9-9ae5-f0105431ab9b.png">

I am also getting the same error when using the docker run command from the readme.md

docker-compose.yml:

```
version: '3.4'

services:

  mailcow-dind:
    image: quay.io/promaethius/mailcow-dind:latest
    container_name: mailcow-dind
    environment:
      - HOSTNAME=220022.xyz
      - CRON_BACKUP=* * * 0 0 *
      - CRON_UPDATE=0 0 * * 0 *
      - TIMEZONE=PDT
    privileged: true
    network_mode: host
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 465:465
      - 587:587
      - 143:143
      - 993:993
      - 110:110
      - 995:995
      - 4190:4190
    deploy:
      replicas: 1
    volumes:
      - /opt/data/volumes:/mnt:rw
      - /opt/data/mailcow:/mailcow:rw
      - /opt/data/mailcow-backup:/mailcow-backup:rw
      - /lib/modules:/lib/modules:ro
``

But anyways thanks for creating this :)

**Comment by Promaethius** [comment]
This could have been an issue belonging to incorrectly labeled stable.
More consistent builds are happening at: https://labs.theshire.space/promaethius/mailcow-dind
